import type { NextPage } from 'next';
import Link from 'next/link'
import Head from 'next/head';

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>home page</h1>
        <Link href='/notes/coffee'>
          <a>read more</a>
        </Link>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}

export default Login;
